title: Nathan Arias # your name (or website title) here
logo: "/images/portfolio_image.png?raw=true" # your photo (or logo) here
description: |
  <br> <br>
  
  Hello I'm Nathan! I am a molecular biologist turned data scientist with a concentration in computer vision, ML, and data visualization. As a scientist at Omeat and an imminent UC Berkeley Data Science Master’s graduate, I am enthusiastic about applying my diverse expertise to innovate across various tech sectors, always ready for new challenges and breakthroughs.
  <br> <br>
  Los Angeles, CA 
  <br> <br>
  <a href="https://github.com/hillarias"><img src="images/github-mark.png?raw=true" alt="GitHub" width="30" height="30"/></a>
  <a href="https://www.linkedin.com/in/nathanarias/"><img src="images/LI-In-Bug.png?raw=true" alt="LinkedIn" width="40" height="30"/></a>

remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
