title: Nathan Arias # your name (or website title) here
logo: "/images/portfolio_image.png?raw=true" # your photo (or logo) here
description: |
  <br> <br>


  Data Scientist / Molecular Biologist
  <br> <br>
  Los Angeles, CA 
  <br> <br>
  <a href="https://github.com/hillarias"><img src="images/github-mark.png?raw=true" alt="GitHub" width="30" height="30"/></a>
  <a href="https://www.linkedin.com/in/nathanarias/"><img src="images/LI-In-Bug.png?raw=true" alt="LinkedIn" width="30" height="40"/></a>

remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
